EJERCICIO 1
SELECT AVG(SALARIO) 
FROM EMPLE
WHERE DEPT_NO = (SELECT DEPT_NO FROM DEPART WHERE DNOMBRE = 'VENTAS')
/
EJERCICIO 2
SELECT EMP_NO, APELLIDO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO = (SELECT DEPT_NO FROM EMPLE WHERE APELLIDO = 'JIMENEZ')
/
EJERCICIO 3
SELECT EMP_NO, APELLIDO, OFICIO 
FROM EMPLE
WHERE OFICIO = (SELECT OFICIO FROM EMPLE WHERE APELLIDO = 'GIL')
/
EJERCICIO 4
SELECT EMP_NO, APELLIDO, OFICIO, DEPT_NO
FROM EMPLE
WHERE OFICIO = (SELECT OFICIO FROM EMPLE WHERE APELLIDO = 'JIMENEZ')
AND DEPT_NO = (SELECT DEPT_NO FROM EMPLE WHERE APELLIDO = 'ALONSO')
/
EJERCICIO 5
SELECT COUNT(EMP_NO)
FROM EMPLE
WHERE DEPT_NO = 10
/
EJERCICIO 6
SELECT EMP_NO, APELLIDO, OFICIO
FROM EMPLE
WHERE OFICIO = '%o%'
EJERCICIO 7
SELECT EMP_NO, APELLIDO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO IN (10, 20)
/
EJERCICIO 8
SELECT TEMA
FROM LIBRERIA
WHERE EJEMPLARES > 10
/
EJERCICIO 9
SELECT EMP_NO, APELLIDO, SALARIO, OFICIO
FROM EMPLE
WHERE (OFICIO, SALARIO) IN (
     SELECT OFICIO, MAX(SALARIO)
	 FROM EMPLE
	 GROUP BY OFICIO
);
EJERCICIO 10
SELECT APELLIDO, SALARIO, DEPT_NO
FROM EMPLE E1
WHERE SALARIO = (SELECT MIN(SALARIO) FROM EMPLE E2 WHERE E1.DEPT_NO = E2.DEPT_NO)
/
EJERCICIO 11
SELECT APENOM, NOMBRE, NOTA
FROM ALUMNOS, ASIGNATURAS, NOTAS
WHERE ALUMNOS.DNI = NOTAS.DNI
AND NOTAS.COD = ASIGNATURAS.COD
AND NOMBRE = 'FOL'
AND NOTA < 5
/
EJERCICIO 12
SELECT DISTINCT APENOM
FROM ASIGNATURAS, NOTAS, ALUMNOS
WHERE ALUMNOS.POBLA = 'Madrid'
AND ALUMNOS.DNI = NOTAS.DNI
AND NOTAS.COD = ASIGNATURAS.COD
AND NOTA < 5;
EJERCICIO 13
SELECT DISTINCT APENOM
FROM ALUMNOS, ASIGNATURAS, NOTAS
WHERE ALUMNOS.DNI = NOTAS.DNI
AND NOTAS.COD = ASIGNATURAS.COD
AND NOTA = (SELECT NOTA FROM ALUMNOS, NOTAS, ASIGNATURAS
WHERE ALUMNOS.DNI = NOTAS.DNI
AND NOTAS.COD = ASIGNATURAS.COD
AND APENOM = 'Díaz Fernández, María'
AND NOMBRE = 'FOL');
EJERCICIO 14
SELECT * FROM ASIGNATURAS
WHERE COD NOT IN (SELECT DISTINCT COD FROM NOTAS);
EJERCICIO 15
SELECT APENOM FROM ALUMNOS
WHERE DNI IN (SELECT DNI FROM NOTAS WHERE COD = 1);
EJERCICIO 16
SELECT APENOM FROM ALUMNOS
WHERE DNI NOT IN (SELECT DNI FROM NOTAS WHERE COD = 1);