EJERCICIO 1
SELECT APELLIDO, OFICIO, LOC FROM EMPLE, DEPART
WHERE OFICIO='ANALISTA'
/
EJERCICIO 2
SELECT * FROM EMPLE
WHERE DIR= (SELECT EMP_NO FROM EMPLE WHERE OFICIO='DIRECTOR' AND APELLIDO= 'CEREZO')
/
EJERCICIO 3
SELECT*FROM EMPLE
WHERE DEPT_NO = (SELECT DEPT_NO FROM DEPART WHERE DNOMBRE='VENTAS')
/
EJERCICIO 4
SELECT * FROM DEPART
WHERE DEPT_NO NOT IN (SELECT DISTINCT DEPT_NO FROM EMPLE)
/
EJERCICIO 5
SELECT * FROM DEPART
WHERE EXISTS (SELECT * FROM EMPLE, DEPART WHERE EMPLE.DEPT_NO = DEPART.DEPT_NO)
/
EJERCICIO 6
SELECT APELLIDO, SALARIO FROM EMPLE
WHERE SALARIO > (SELECT MAX (SALARIO) FROM EMPLE WHERE DEPT_NO=20)
/
EJERCICIO 7
SELECT * FROM LIBRERIA WHERE EJEMPLARES BETWEEN 8 AND 15
/
EJERCICIO 8
SELECT TEMA, ESTANTE, EJEMPLARES FROM LIBRERIA
WHERE ESTANTE NOT BETWEEN 'B' AND 'D'
/
EJERCICIO 9
SELECT TEMA FROM LIBRERIA
WHERE EJEMPLARES < (SELECT EJEMPLARES FROM LIBRERIA WHERE TEMA ='MEDICINA')
 /
EJERCICIO 10
SELECT TEMA FROM LIBRERIA WHERE EJEMPLARES NOT BETWEEN 15 AND 20
/
EJERCICIO 11
SELECT * FROM ASIGNATURAS
WHERE NOMBRE LIKE '%O%' AND COD IN (SELECT COD FROM NOTAS
WHERE DNI IN (SELECT DNI FROM ALUMNOS WHERE POBLA='Madrid'))
/
EJERCICIO 12
SELECT APENOM FROM ALUMNOS
WHERE POBLA='Madrid' AND DNI IN (SELECT DNI FROM NOTAS WHERE NOTA<5)
/
EJERCICIO 13
SELECT DISTINCT APENOM FROM ALUMNOS, NOTAS WHERE NOTA IN (SELECT NOTA FROM NOTAS WHERE COD IN
(SELECT COD FROM ASIGNATURAS WHERE NOMBRE='FOL')AND DNI IN (SELECT DNI FROM ALUMNOS
WHERE APENOM='Díaz Fernández, María') AND ALUMNOS.DNI=NOTAS.DNI)
/
EJERCICIO 14
SELECT * FROM ASIGNATURAS
WHERE COD NOT IN (SELECT COD FROM NOTAS)
/
EJERCICIO 15
SELECT APENOM FROM ALUMNOS, NOTAS
WHERE ALUMNOS.DNI = NOTAS.DNI 
AND COD = 1
/
EJERCICIO 16
SELECT UNIQUE APENOM FROM ALUMNOS
WHERE DNI NOT IN (SELECT DNI FROM NOTAS WHERE COD = 1)
/
