EJERCICIO 1
SELECT EMP_NO, APELLIDO, DEPT_NO, SALARIO
FROM EMPLE
WHERE SALARIO = (SELECT MAX(SALARIO) FROM EMPLE WHERE DEPT_NO = 10)
/
EJERCICIO 2
SELECT EMP_NO, APELLIDO, DEPT_NO, SALARIO
FROM EMPLE
WHERE SALARIO < (SELECT AVG(SALARIO) FROM EMPLE WHERE DEPT_NO = 20)
AND DEPT_NO = 20
/
EJERCICIO 3
SELECT EMP_NO, APELLIDO, OFICIO
FROM EMPLE
WHERE SALARIO > (SELECT AVG(SALARIO) FROM EMPLE WHERE OFICIO = 'VENDEDOR')
AND OFICIO = 'VENDEDOR'
/
EJERCICIO 4
SELECT EMP_NO, APELLIDO, SALARIO, DEPT_NO
FROM EMPLE
WHERE SALARIO > (SELECT AVG(SALARIO) FROM EMPLE WHERE DEPT_NO = 20)
/
EJERCICIO 5
SELECT EMP_NO, APELLIDO, SALARIO
FROM EMPLE
WHERE SALARIO > (SELECT AVG(SALARIO) FROM EMPLE)
/
EJERCICIO 6
SELECT GREATEST(MAX(NOTA1),MAX(NOTA2),MAX(NOTA3))"MAYOR NOTA" 
FROM NOTAS_ALUMNOS
/
EJERCICIO 7
SELECT NOMBRE_ALUMNO, NOTA1, NOTA2, NOTA3
FROM NOTAS_ALUMNOS
WHERE NOTA1 = (SELECT GREATEST(MAX(NOTA1),MAX(NOTA2),MAX(NOTA3)) FROM NOTAS_ALUMNOS)
OR NOTA2 = (SELECT GREATEST(MAX(NOTA1),MAX(NOTA2),MAX(NOTA3)) FROM NOTAS_ALUMNOS)
OR NOTA3 = (SELECT GREATEST(MAX(NOTA1),MAX(NOTA2),MAX(NOTA3)) FROM NOTAS_ALUMNOS)
/
EJERCICIO 8
SELECT TITULO FROM MISTEXTOS WHERE TITULO LIKE '% % %'
/
EJERCICIO 9
SELECT AUTOR || ' escribió ' || TITULO FROM MISTEXTOS
/
EJERCICIO 10
SELECT APELLIDO, TRUNC((SYSDATE-FECHA_ALT)/365) FROM EMPLE WHERE TRUNC((SYSDATE-FECHA_ALT)/365) > 25
/
EJERCICIO 11
SELECT * FROM EMPLE E WHERE FECHA_ALT = (SELECT MIN(FECHA_ALT) FROM EMPLE WHERE DEPT_NO = E.DEPT_NO)
/
EJERCICIO 12
SELECT * FROM EMPLE E WHERE FECHA_ALT = (SELECT MAX(FECHA_ALT) FROM EMPLE WHERE OFICIO = E.OFICIO)
/
EJERCICIO 13
SELECT TO_CHAR(SYSDATE,' "Hoy es " dd " de " mm "de" yyyy') FROM DUAL
/
EJERCICIO 14
SELECT TO_CHAR(SYSDATE, 'dd "-" mm "-" yy') FROM DUAL
/
EJERCICIO 15
SELECT TRUNC((TO_DATE('01/01/2030' , 'DD/MM/YYYY') - sysdate)) FROM DUAL
/
EJERCICIO 16
SELECT TRUNC(SYSDATE - TO_DATE('01/01/2001', 'DD/MM/YYYY')) "DÍAS DESDE EL INICIO DE SIGLO" FROM DUAL
/
EJERCICIO 17
SELECT ADD_MONTHS(FECHA_VENTA,2) FROM VENTAS
/
EJERCICIO 18
SELECT TO_DATE(sysdate , 'DD/MM/YYYY') FROM DUAL
/
EJERCICIO 19
SELECT SUBSTR(AUTOR, INSTR(AUTOR, ',' )+ 2) || ' ' || SUBSTR(AUTOR, 1, INSTR(AUTOR, ',' )- 1) FROM LIBROS
/